### ISSUE TITLE
Regeneration is also triggered when moving main task date

### ISSUE THREAD

**Issue by JoergBr** [Hoffelhas/automation-todoist#8] opened 2021-02-02 12:37 UTC
Hello again, yesterday I moved a main task with @Regen_all tag from one day to another after completing a few (but not all) subtasks. To my surprise, the completed subtasks were regenerated even though I didn't complete the recurring main task.

Is this by design? I would expect that the subtasks are only regenerated when I complete (= tick off) the main task. Or is it a problem to distinguish if a recurring task as just been moved or completed?

**Comment by Hoffelhas** [comment] 2023-01-10 19:49
Hi, this is indeed not the intended behavior. In any case, for the next release the current implementation of this regeneration feature will likely be removed, since Todoist now natively supports this. (Well ok it's experimental, but check out 'Resetting sub-tasks upon parent task completion' [which can be found here](https://todoist.com/help/articles/experimental-features).

EDIT: no, it's now actually [part of core Todoist.](https://todoist.com/help/articles/can-i-reset-sub-tasks))

Even so, it's still not working exactly as I would like. So perhaps in the future I will try to supplement the workings with Autodoist, but for now I will close this issue.

**Closed as completed by Hoffelhas** 2023-01-10 19:49 UTC
